### ISSUE TITLE
A Problem when Creating Representations - Indexing

### ISSUE THREAD

**Issue by XX-Official** [tech-srl/Nero#10]
When I using :
python3 -u index_binaries.py --input-dir TRAIN --output-dir TRAIN_INDEXED

an error occurred：
INFO:cle.backends.binja:Unable to import binaryninja module
Traceback (most recent call last):
  File "Nero-main/index_binaries.py", line 7, in <module>
    from datagen.index_engine_core import index_object, my_aggregated_md5s_with_llvm, is_indexed, \
  File "/home/Nero-main/datagen/index_engine_core.py", line 23, in <module>
    from .llvmcpy_helpers import ProcedureIndexTimeout, signal_handler
  File "/home/Nero-main/datagen/llvmcpy_helpers.py", line 8, in <module>
    from llvmcpy.llvm import *
  File "/usr/local/lib/python3.8/dist-packages/llvmcpy/llvm.py", line 803, in <module>
    llvm_config = find_program("LLVM_CONFIG", ["llvm-config"])
  File "/usr/local/lib/python3.8/dist-packages/llvmcpy/llvm.py", line 42, in find_program
    raise RuntimeError("Couldn't find "
RuntimeError: Couldn't find LLVM_CONFIG or any of the following executables in PATH: llvm-config

**Comment by Yanivmd** [comment]
It seems that llvm-config is not in your path.
Did you install LLVM (version) 10 and put `llvm-config` and the rest of LLVM's binaries in $PATH?

**Comment by nav60** [comment]
it works perfectly on Ubuntu 20 and install requirements.txt

**Comment by XX-Official** [comment]
another error occurred：
INFO:cle.backends.binja:Unable to import binaryninja module
WARNING  | root | Creating TMPFS of size 211095371.19921875MB - you might need to provide a password (common_functions.py:274)
mount: /tmp/tmpfs: permission denied.
ERROR    | root | Error breaking name - [ (allow_list.py:44)
ERROR    | root | multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.8/dist-packages/parmap/parmap.py", line 116, in _func_star_many
    return func_items_args[0](*list(func_items_args[1]) + func_items_args[2],
  File "/home/Nero-main/datagen/index_engine_core.py", line 121, in index_object
    name_parts = break_name(object_name)
  File "/home/Nero-main/datagen/common/allow_list.py", line 45, in break_name
    raise ValueError
ValueError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/Nero-main/datagen/common/common_functions.py", line 373, in run_as_main
    main(input_args)
  File "Nero-main/index_binaries.py", line 61, in main
    for _ in tqdm(mapper(index_object, to_work, pm_chunksize=1)):
  File "/usr/local/lib/python3.8/dist-packages/parmap/parmap.py", line 324, in starmap
    return _map_or_starmap(function, iterables, args, kwargs, "starmap")
  File "/usr/local/lib/python3.8/dist-packages/parmap/parmap.py", line 248, in _map_or_starmap
    output = result.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError
 (common_functions.py:376)

**Comment by Yanivmd** [comment]
The input binary files need to be in this format:
`<compiler>-<compiler version>__O<Optimization level(u for default)>__<Package name>[-<optional package version>]__<Executable name> `

Otherwise, "break_name" will fail.

**Comment by nav60** [comment]
I have already run NERO for basic understanding of the concept. however, above error is strange "I**NFO:cle.backends.binja:Unable to import binaryninja module**"  because it uses the IDA-PRO licensed to start the indexing process.

**Comment by Yanivmd** [comment]
This error comes from angr/one of its dependents. You can safely ignore it.

**Comment by Yanivmd** [comment]
All questions/problems raised were addressed. Please re-open if that is not the case.
